# -*- coding: utf-8 -*-
"""tabnet_neoplasias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198G6Sog9xw3TNMhrkV68o108krwiFkdl

* Estimativa populacional segundo ano, sexo, faixa etária e local de residência.
* Município de São Paulo
* População por Dist Adm (DA) e Faixa Etária
* Período:2018
"""

# https://drive.google.com/drive/folders/18MjRzqdVn7dRQTc5I4MVJl9gE_3uZKjI

import pandas as pd

# ID do arquivo no Google Drive
file_id = "1YsiJbfUVWRJhbXRMgJAZC7Q79mSC0HrS"

# Link direto para download
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Ler o CSV pulando as 3 primeiras linhas
df = pd.read_csv(
    download_url,
    encoding="latin1",   # evita o erro de acentuação
    sep=';',             # muito comum em arquivos PT-BR; troque para ',' se não for o caso
    skiprows=4           # pula as 4 primeiras linhas (dados começam na 4ª)
)
# copiar df
df2018 = df.copy()

#coluna ano
df2018["ano"] = 2018
# Ver as primeiras linhas
df2018.head()

# import pandas as pd
# https://drive.google.com/file/d/1XBJUhRDBb5-NGF8zfFLE9PC6X2XURD4N/view?usp=sharing

# ID do arquivo no Google Drive
file_id = "1XBJUhRDBb5-NGF8zfFLE9PC6X2XURD4N"

# Link direto para download
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Ler o CSV pulando as 3 primeiras linhas
df = pd.read_csv(
    download_url,
    encoding="latin1",   # evita o erro de acentuação
    sep=';',             # muito comum em arquivos PT-BR; troque para ',' se não for o caso
    skiprows=3           # pula as 4 primeiras linhas (dados começam na 4ª)
)
# copiar df
df2019 = df.copy()

# coluna ano
df2019["ano"] = 2019
# Ver as primeiras linhas

# rename "Dist Adm (DA)"
df2019 = df2019.rename(columns={"Dist Adm (DA)":"Distrito Admin residência"})
display(df2019.head())
display(df2019.tail())

import pandas as pd

# https://drive.google.com/file/d/19oXY4agxNSTvPInxZcPJru6SclQ9tb_J/view?usp=drive_link

# ID do arquivo no Google Drive
file_id = "19oXY4agxNSTvPInxZcPJru6SclQ9tb_J"

# Link direto para download
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Ler o CSV pulando as 3 primeiras linhas
df = pd.read_csv(
    download_url,
    encoding="latin1",   # evita o erro de acentuação
    sep=';',             # muito comum em arquivos PT-BR; troque para ',' se não for o caso
    skiprows=3           # pula as 4 primeiras linhas (dados começam na 4ª)
)
# copiar df
df2020 = df.copy()

# coluna ano
df2020["ano"] = 2020
# Ver as primeiras linhas

# rename "Dist Adm (DA)"
df2020 = df2020.rename(columns={"Dist Adm (DA)":"Distrito Admin residência"})
display(df2020.head())
display(df2020.tail())

import pandas as pd

# https://drive.google.com/file/d/17jBVRJPXeXGgJtn1JYVjRC6JxD6I2MTQ/view?usp=sharing

# ID do arquivo no Google Drive
file_id = "17jBVRJPXeXGgJtn1JYVjRC6JxD6I2MTQ"

# Link direto para download
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Ler o CSV pulando as 3 primeiras linhas
df = pd.read_csv(
    download_url,
    encoding="latin1",   # evita o erro de acentuação
    sep=';',             # muito comum em arquivos PT-BR; troque para ',' se não for o caso
    skiprows=3           # pula as 4 primeiras linhas (dados começam na 4ª)
)
# copiar df
df2021 = df.copy()

# coluna ano
df2021["ano"] = 2021
# Ver as primeiras linhas

# rename "Dist Adm (DA)"
df2021 = df2021.rename(columns={"Dist Adm (DA)":"Distrito Admin residência"})
display(df2021.head())
display(df2021.tail())

import pandas as pd

# https://drive.google.com/file/d/1ueTy_DAbcwBcLQiBx3XW5pJYLRDZwmtI/view?usp=sharing

# ID do arquivo no Google Drive
file_id = "1ueTy_DAbcwBcLQiBx3XW5pJYLRDZwmtI"

# Link direto para download
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Ler o CSV pulando as 3 primeiras linhas
df = pd.read_csv(
    download_url,
    encoding="latin1",   # evita o erro de acentuação
    sep=';',             # muito comum em arquivos PT-BR; troque para ',' se não for o caso
    skiprows=3           # pula as 4 primeiras linhas (dados começam na 4ª)
)
# copiar df
df2022 = df.copy()

# coluna ano
df2022["ano"] = 2022
# Ver as primeiras linhas

# rename "Dist Adm (DA)"
df2022 = df2022.rename(columns={"Dist Adm (DA)":"Distrito Admin residência"})
display(df2022.head())
display(df2022.tail())

import pandas as pd

# https://drive.google.com/file/d/1M8A1yXCtg10QsFefLS-tp33d-7P6LRRK/view?usp=sharing

# ID do arquivo no Google Drive
file_id = "1M8A1yXCtg10QsFefLS-tp33d-7P6LRRK"

# Link direto para download
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Ler o CSV pulando as 3 primeiras linhas
df = pd.read_csv(
    download_url,
    encoding="latin1",   # evita o erro de acentuação
    sep=';',             # muito comum em arquivos PT-BR; troque para ',' se não for o caso
    skiprows=3           # pula as 4 primeiras linhas (dados começam na 4ª)
)
# copiar df
df2023 = df.copy()

# coluna ano
df2023["ano"] = 2023
# Ver as primeiras linhas

# rename "Dist Adm (DA)"
df2023 = df2023.rename(columns={"Dist Adm (DA)":"Distrito Admin residência"})
display(df2023.head())
display(df2023.tail())

import pandas as pd

# https://drive.google.com/file/d/1x9Akwi3D8eLQnfCX084Kgv_I1fAUJS1c/view?usp=sharing

# ID do arquivo no Google Drive
file_id = "1x9Akwi3D8eLQnfCX084Kgv_I1fAUJS1c"

# Link direto para download
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

# Ler o CSV pulando as 3 primeiras linhas
df = pd.read_csv(
    download_url,
    encoding="latin1",   # evita o erro de acentuação
    sep=';',             # muito comum em arquivos PT-BR; troque para ',' se não for o caso
    skiprows=3           # pula as 4 primeiras linhas (dados começam na 4ª)
)
# copiar df
df2024 = df.copy()

# coluna ano
df2024["ano"] = 2024
# Ver as primeiras linhas

# rename "Dist Adm (DA)"
df2024 = df2024.rename(columns={"Dist Adm (DA)":"Distrito Admin residência"})
display(df2024.head())
display(df2024.tail())

df_anos = pd.concat([df2018,df2019,df2020,df2021,df2022,df2023,df2024])

# rename "Dist Adm (DA)"
df_anos = df_anos.rename(columns={"Dist Adm (DA)":"Distrito Admin residência"})
display(df_anos.head())
display(df_anos.tail())